# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogoLed.ui'
#
# Created: Tue Jun 10 04:36:16 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogoLed(object):
    def setupUi(self, DialogoLed):
        DialogoLed.setObjectName(_fromUtf8("DialogoLed"))
        DialogoLed.resize(757, 589)
        self.frame = QtGui.QFrame(DialogoLed)
        self.frame.setGeometry(QtCore.QRect(150, 0, 411, 171))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.lineEdit_2 = QtGui.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 80, 113, 25))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit = QtGui.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(290, 80, 113, 25))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 60, 81, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(160, 130, 111, 26))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(320, 60, 58, 15))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.frame_2 = QtGui.QFrame(DialogoLed)
        self.frame_2.setGeometry(QtCore.QRect(120, 160, 501, 121))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(370, 40, 58, 15))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(30, 60, 58, 15))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(40, 80, 58, 15))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(440, 40, 58, 15))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(90, 60, 58, 15))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(400, 80, 58, 15))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.frame_3 = QtGui.QFrame(DialogoLed)
        self.frame_3.setGeometry(QtCore.QRect(30, 280, 701, 301))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.progressBar = QtGui.QProgressBar(self.frame_3)
        self.progressBar.setGeometry(QtCore.QRect(150, 60, 118, 23))
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.progressBar_3 = QtGui.QProgressBar(self.frame_3)
        self.progressBar_3.setGeometry(QtCore.QRect(520, 50, 118, 23))
        self.progressBar_3.setProperty("value", 100)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))
        self.label_9 = QtGui.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(110, 270, 58, 15))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.progressBar_2 = QtGui.QProgressBar(self.frame_3)
        self.progressBar_2.setGeometry(QtCore.QRect(150, 120, 118, 23))
        self.progressBar_2.setMaximum(30)
        self.progressBar_2.setProperty("value", 30)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.label_18 = QtGui.QLabel(self.frame_3)
        self.label_18.setGeometry(QtCore.QRect(300, 260, 58, 15))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_14 = QtGui.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(400, 180, 71, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_21 = QtGui.QLabel(self.frame_3)
        self.label_21.setGeometry(QtCore.QRect(180, 30, 58, 15))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_15 = QtGui.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(210, 220, 58, 15))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_13 = QtGui.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(300, 180, 58, 15))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_22 = QtGui.QLabel(self.frame_3)
        self.label_22.setGeometry(QtCore.QRect(170, 90, 58, 15))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_11 = QtGui.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(110, 180, 58, 15))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_24 = QtGui.QLabel(self.frame_3)
        self.label_24.setGeometry(QtCore.QRect(540, 80, 58, 15))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.progressBar_4 = QtGui.QProgressBar(self.frame_3)
        self.progressBar_4.setGeometry(QtCore.QRect(530, 110, 118, 23))
        self.progressBar_4.setMaximum(30)
        self.progressBar_4.setProperty("value", 30)
        self.progressBar_4.setObjectName(_fromUtf8("progressBar_4"))
        self.label_10 = QtGui.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(110, 220, 58, 15))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_19 = QtGui.QLabel(self.frame_3)
        self.label_19.setGeometry(QtCore.QRect(400, 220, 58, 15))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_12 = QtGui.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(210, 180, 58, 15))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_17 = QtGui.QLabel(self.frame_3)
        self.label_17.setGeometry(QtCore.QRect(300, 220, 58, 15))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_20 = QtGui.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(400, 260, 58, 15))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_23 = QtGui.QLabel(self.frame_3)
        self.label_23.setGeometry(QtCore.QRect(550, 20, 58, 15))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_16 = QtGui.QLabel(self.frame_3)
        self.label_16.setGeometry(QtCore.QRect(210, 260, 58, 15))
        self.label_16.setObjectName(_fromUtf8("label_16"))

        self.retranslateUi(DialogoLed)
        QtCore.QMetaObject.connectSlotsByName(DialogoLed)

    def retranslateUi(self, DialogoLed):
        DialogoLed.setWindowTitle(_translate("DialogoLed", "Controle de Led", None))
        self.label.setText(_translate("DialogoLed", "Jogador 1", None))
        self.pushButton.setText(_translate("DialogoLed", "Iniciar jogo", None))
        self.label_4.setText(_translate("DialogoLed", "Jogador 2", None))
        self.label_8.setText(_translate("DialogoLed", "Jogador2:", None))
        self.label_7.setText(_translate("DialogoLed", "Jogador1:", None))
        self.label_5.setText(_translate("DialogoLed", "A espera", None))
        self.label_2.setText(_translate("DialogoLed", "label_2", None))
        self.label_3.setText(_translate("DialogoLed", "label_3", None))
        self.label_6.setText(_translate("DialogoLed", "A espera", None))
        self.label_9.setText(_translate("DialogoLed", "label9", None))
        self.progressBar_2.setFormat(_translate("DialogoLed", "%v", None))
        self.label_18.setText(_translate("DialogoLed", "0", None))
        self.label_14.setText(_translate("DialogoLed", "hedashots", None))
        self.label_21.setText(_translate("DialogoLed", "Vida", None))
        self.label_15.setText(_translate("DialogoLed", "0", None))
        self.label_13.setText(_translate("DialogoLed", "derrotas", None))
        self.label_22.setText(_translate("DialogoLed", "municoes", None))
        self.label_11.setText(_translate("DialogoLed", "Jogador", None))
        self.label_24.setText(_translate("DialogoLed", "municoes", None))
        self.progressBar_4.setFormat(_translate("DialogoLed", "%v", None))
        self.label_10.setText(_translate("DialogoLed", "label10", None))
        self.label_19.setText(_translate("DialogoLed", "0", None))
        self.label_12.setText(_translate("DialogoLed", "vitorias", None))
        self.label_17.setText(_translate("DialogoLed", "0", None))
        self.label_20.setText(_translate("DialogoLed", "0", None))
        self.label_23.setText(_translate("DialogoLed", "Vida", None))
        self.label_16.setText(_translate("DialogoLed", "0", None))

